### PR TITLE
Two fixes for -o behavior

### PR DESCRIPTION
**Pull request by BryanAldrich**
setting the current directory when using -o causes issues loading templates (which read from current (skyrim data)).

create the missing output directory if it does not already exist.

### CODE REVIEW

**Comment by BryanAldrich** [comment]
my intention for this is to have pandora installed outside of everything, -o point to an empty folder (that gets packaged into a mod of its own).

What I don't know is what to do if there are templates in both the launch folder + the skyrim\data folder that are pointing to the same template. e.g. one overwrites/updates part of a template that is in the launch folder. Who wins?

**Comment by Monitor221hz** [comment]
Why would you ever have template folders in both the launch and the skyrim\data folder? The template folders should be unseparable from the base engine as it requires those to launch.

**Comment by BryanAldrich** [comment]
I mean from mods that alter the templates.

Like Archery Gameplay Overhaul. It has a Nemesis patch which puts files in the Nemesis_Engine folder.

https://www.nexusmods.com/skyrimspecialedition/mods/24296?tab=files

I'm also thinking of the "possible, but does it happen?" cases where someone posts mods to your templates to either acomodate their other mods or to change behavior. (khajit that walk on their toes vs feet).

**Comment by Monitor221hz** [comment]
There was a migration to Avalonia so this PR could not be carried over; however, the changes were recreated; see here: https://github.com/Monitor221hz/Pandora-Behaviour-Engine-Plus/pull/291/commits/bb0238d28d88883d4115b72934a42cede613c5a6

**Pull request closed without merging**
